FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

RUN sed -i 's/\[openssl_init\]/# [openssl_init]/' /etc/ssl/openssl.cnf &&\
    printf "\n\n[openssl_init]\nssl_conf = ssl_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_sect]\nsystem_default = ssl_default_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT@SECLEVEL=0\n" >> /etc/ssl/openssl.cnf

RUN apt-get update && apt-get install -y --no-install-recommends curl

WORKDIR /app

COPY Gnoss.Web.Ontologies/*.csproj ./

RUN dotnet restore

COPY . ./

RUN dotnet publish Gnoss.Web.Ontologies/Gnoss.Web.Ontologies.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

RUN sed -i 's/\[openssl_init\]/# [openssl_init]/' /etc/ssl/openssl.cnf &&\
    printf "\n\n[openssl_init]\nssl_conf = ssl_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_sect]\nsystem_default = ssl_default_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT@SECLEVEL=0\n" >> /etc/ssl/openssl.cnf

RUN apt-get update && apt-get install -y --no-install-recommends curl

WORKDIR /app

RUN groupadd -g 1000 gnoss && useradd -u 1000 -g 1000 gnoss &&\
	mkdir -p logs trazas Ontologias archivos Mapping &&\
	chown -R gnoss:gnoss logs trazas Ontologias archivos Mappin &&\
	chmod -R 777 logs trazas Ontologias archivos Mappin
USER gnoss

COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Gnoss.Web.Ontologies.dll"]
